/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dbpan
 */
public class frmDetallePlanilla extends javax.swing.JFrame {

    private int idPlanilla;

    /**
     * Creates new form frmDetallePlanilla
     */
    public frmDetallePlanilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPlanilla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTSBruto = new javax.swing.JLabel();
        lblTSNeto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Calculo de planilla");

        jtPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#PLANILLA", "FECHA", "CEDULA", "NOMBRE", "APELLIDO", "HT", "SxH", "SALARIO BRUTO", "SS", "SE", "SALARIO NETO"
            }
        ));
        jtPlanilla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtPlanillaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtPlanilla);

        jLabel2.setText("Total Salario Bruto: ");

        jLabel3.setText("Total Salario neto:");

        lblTSBruto.setText("xxxxx");

        lblTSNeto.setText("xxxxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTSBruto)
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTSNeto)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblTSBruto)
                    .addComponent(lblTSNeto))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void setIdPlanilla(int idPlanilla) {
        System.out.println("Desde el metodo id Planilla " + idPlanilla);
        this.idPlanilla = idPlanilla;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        cargarDetallePlanilla(); // Cargar los detalles de la planilla al abrir el formulario
    }

    public void cargarDetallePlanilla() {
        DefaultTableModel modelo = (DefaultTableModel) jtPlanilla.getModel();

        // Luego, limpiamos cualquier contenido que pueda haber en la tabla actualmente
        modelo.setRowCount(0);
        DefaultTableModel modeloDetalle = (DefaultTableModel) jtPlanilla.getModel();
        modeloDetalle.setRowCount(0); // Limpiar el contenido actual de la tabla jtPlanilla

        MostrarDetallePlanilla obj_detalle_planilla = new MostrarDetallePlanilla();
        System.out.println("Desde el metodo cargarDetallePlanilla " + idPlanilla);
        ArrayList<MostrarDetallePlanilla> lista_detalle = obj_detalle_planilla.mostrar_detalle_planillas(this.idPlanilla);

        for (MostrarDetallePlanilla detalle : lista_detalle) {
            String[] arregloDetalle = {
                String.valueOf(detalle.getId_detalle_planilla()),
                String.valueOf(detalle.getFecha_creacion()),
                detalle.getCedula_empleado(),
                detalle.getNombre_empleado(),
                detalle.getApellido_empleado(),
                String.valueOf(detalle.getHoras_trabajadas()),
                String.valueOf(detalle.getSalario_por_hora()),
                String.valueOf(detalle.getSalario_bruto()),
                String.valueOf(detalle.getSeguro_social()),
                String.valueOf(detalle.getSeguro_educativo()),
                String.valueOf(detalle.getSalario_neto()),
                String.valueOf(detalle.getTotal_salario_bruto()),
                String.valueOf(detalle.getTotal_salario_neto())
            };
            modeloDetalle.addRow(arregloDetalle);
            lblTSBruto.setText("T.S. Bruto: " + String.valueOf(detalle.getTotal_salario_bruto()));
            lblTSNeto.setText("T.S. Neto: " + String.valueOf(detalle.getTotal_salario_neto()));
        }

    }


    private void jtPlanillaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtPlanillaPropertyChange

    }//GEN-LAST:event_jtPlanillaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetallePlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPlanilla;
    private javax.swing.JLabel lblTSBruto;
    private javax.swing.JLabel lblTSNeto;
    // End of variables declaration//GEN-END:variables
}
